package com.example.backend.models.user;

public enum Role
{
    USER,
    SITE_ADMIN,
    PROCUREMENT,
    WAREHOUSE_MANAGER,
    SECRETARY,
    EQUIPMENT_MANAGER,
    HR_MANAGER,
    HR_EMPLOYEE,
    FINANCE_MANAGER,
    FINANCE_EMPLOYEE,
    MAINTENANCE_EMPLOYEE,
    MAINTENANCE_MANAGER,
    ADMIN;
}
