// Role constants for use throughout the frontend
export const ADMIN = 'ADMIN';
export const USER = 'USER';
export const SITE_ADMIN = 'SITE_ADMIN';
export const PROCUREMENT = 'PROCUREMENT';
export const WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER';
export const WAREHOUSE_EMPLOYEE = 'WAREHOUSE_EMPLOYEE';
export const SECRETARY = 'SECRETARY';
export const EQUIPMENT_MANAGER = 'EQUIPMENT_MANAGER';
export const HR_MANAGER = 'HR_MANAGER';
export const HR_EMPLOYEE = 'HR_EMPLOYEE';
export const FINANCE_MANAGER = 'FINANCE_MANAGER';
export const FINANCE_EMPLOYEE = 'FINANCE_EMPLOYEE';
export const MAINTENANCE_MANAGER = 'MAINTENANCE_MANAGER';
export const MAINTENANCE_EMPLOYEE = 'MAINTENANCE_EMPLOYEE';

// Export all as a single object for convenience
export const ROLES = {
  ADMIN,
  USER,
  SITE_ADMIN,
  PROCUREMENT,
  WAREHOUSE_MANAGER,
  WAREHOUSE_EMPLOYEE,
  SECRETARY,
  EQUIPMENT_MANAGER,
  HR_MANAGER,
  HR_EMPLOYEE,
  FINANCE_MANAGER,
  FINANCE_EMPLOYEE,
  MAINTENANCE_MANAGER,
  MAINTENANCE_EMPLOYEE,
};